<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>bin\Debug\net8.0-windows\halcondotnet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
