<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\HistoryRecordView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>