<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ViewModels\PreviousTempAndCaliDebugViewModel.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AVS_Common\AVS_Common.csproj" />
    <ProjectReference Include="..\AVS_Drivers\AVS_Drivers.csproj" />
    <ProjectReference Include="..\AVS_VisionService\AVS_Service.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>..\AVS_Common\bin\Debug\net48\halcondotnet.dll</HintPath>
    </Reference>
    <Reference Include="MMDeployCSharp">
      <HintPath>..\AVS_Common\bin\Debug\net48\MMDeployCSharp.dll</HintPath>
    </Reference>
    <Reference Include="OpenCvSharp">
      <HintPath>..\AVS_Common\bin\Debug\net48\OpenCvSharp.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="WindowsFormsIntegration" />
  </ItemGroup>
</Project>