<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Modules\**" />
    <EmbeddedResource Remove="Modules\**" />
    <None Remove="Modules\**" />
    <Page Remove="Modules\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AVS_Common\AVS_Common.csproj" />
    <ProjectReference Include="..\AVS_Core\AVS_Core.csproj" />
    <ProjectReference Include="..\AVS_Modules_Data\AVS_Modules_Data.csproj" />
    <ProjectReference Include="..\AVS_Modules_Settings\AVS_Modules_Settings.csproj" />
    <ProjectReference Include="..\AVS_VisionService\AVS_Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>..\AVS_Common\bin\x64\Debug\net8.0-windows\halcondotnet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
